---
title: "Publications"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---
These papers were written using HADES.

# Clinical application

- Voss EA, Ali SR, Singh A, et al. [Hip Fracture Risk After Treatment with Tramadol or Codeine: An Observational Study](https://doi.org/10.1007/s40264-022-01198-9) Drug Saf. 2022 Jul;45(7):791-807.

- Li X, Ostropolets A, Makadia R, Shoaibi A, et al. [Characterising the background incidence rates of adverse events of special interest for covid-19 vaccines in eight countries: multinational network cohort study](https://doi.org/10.1136/bmj.n1435) BMJ. 2021 Jun 14;373:n1435.

- Shoaibi A, Rao GA, Voss EA,  et al. [Phenotype Algorithms for the Identification and Characterization of Vaccine-Induced Thrombotic Thrombocytopenia in Real World Data: A Multinational Network Cohort Study](https://doi.org/10.1007/s40264-022-01187-y) Drug Saf. 2022 Jun;45(6):685-698.

- Reps JM, Wilcox M, McGee BA, et al. [Development of multivariable models to predict perinatal depression before and after delivery using patient reported survey responses at weeks 4-10 of pregnancy](https://bmcpregnancychildbirth.biomedcentral.com/articles/10.1186/s12884-022-04741-9) BMC Pregnancy Childbirth. 2022 May 26;22(1):442. doi: 10.1186/s12884-022-04741-9.

- Williams RD, Markus AF, Yang C, et al. [Seek COVER: using a disease proxy to rapidly develop and validate a personalized risk calculator for COVID-19 outcomes in an international network](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-022-01505-z) BMC Med Res Methodol. 2022 Jan 30;22(1):35. doi: 10.1186/s12874-022-01505-z.

- Nestsiarovich A, Reps JM, Matheny ME, et al. [Predictors of diagnostic transition from major depressive disorder to bipolar disorder: a retrospective observational network study](https://doi.org/10.1038/s41398-021-01760-6) Transl Psychiatry. 2021 Dec 20;11(1):642.

- Williams RD, Reps JM; OHDSI/EHDEN Knee Arthroplasty Group, et al. [90-Day all-cause mortality can be predicted following a total knee replacement: an international, network study to develop and validate a prediction model](https://dx.doi.org/10.1007/s00167-021-06799-y) Knee Surg Sports Traumatol Arthrosc. 2021 Dec 6. doi: 10.1007/s00167-021-06799-y.

- Chen R, Suchard MA, Krumholz HM, et al. [Comparative First-Line Effectiveness and Safety of ACE (Angiotensin-Converting Enzyme) Inhibitors and Angiotensin Receptor Blockers: A Multinational Cohort Study](https://www.ahajournals.org/doi/10.1161/HYPERTENSIONAHA.120.16667?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed) Hypertension. 2021 Sep;78(3):591-603. doi: 10.1161/HYPERTENSIONAHA.120.16667.

- Chan You S, Krumholz HM, Suchard MA, et al. [Comprehensive Comparative Effectiveness and Safety of First-Line β-Blocker Monotherapy in Hypertensive Patients: A Large-Scale Multicenter Observational Study](https://doi.org/10.1161/hypertensionaha.120.16402) Hypertension
. 2021 May 5;77(5):1528-1538. doi: 10.1161/HYPERTENSIONAHA.120.16402.

- Morales DR, Conover MM, You SC, et al. [Renin-angiotensin system blockers and susceptibility to COVID-19: an international, open science, cohort analysis.](https://doi.org/10.1016/S2589-7500(20)30289-2) Lancet Digit Health. 2020 Dec 17:S2589-7500(20)30289-2. doi: 10.1016/S2589-7500(20)30289-2. 

- You SC, Rho Y, Bikdeli B, et al. [Association of Ticagrelor vs Clopidogrel With Net Adverse Clinical Events in Patients With Acute Coronary Syndrome Undergoing Percutaneous Coronary Intervention.](https://doi.org/10.1001/jama.2020.16167) JAMA. 2020 Oct 27;324(16):1640-1650. doi: 10.1001/jama.2020.16167.

- Burn E, You SC, Sena AG, et al. [Deep phenotyping of 34,128 adult patients hospitalised with COVID-19 in an international network study.](https://doi.org/10.1038/s41467-020-18849-z) Nat Commun. 2020 Oct 6;11(1):5009. doi: 10.1038/s41467-020-18849-z.

- Lane JCE, Weaver J, Kostka K, et al. [Risk of hydroxychloroquine alone and in combination with azithromycin in the treatment of rheumatoid arthritis: a multinational, retrospective study.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7442425/) Lancet Rheumatology. 2020 Aug 21.

- Kim Y, Tian Y, Yang J, et al. [Comparative safety and effectiveness of alendronate versus raloxifene in women with osteoporosis.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7338498/) Sci Rep. 2020 Jul 6;10(1):11115. 

- Hripcsak G, Suchard MA, Shea S, et al. [Comparison of Cardiovascular and Safety Outcomes of Chlorthalidone vs Hydrochlorothiazide to Treat Hypertension.](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2760777) JAMA Intern Med. 2020 Feb 17.

- Reps JM, Cepeda MS, Ryan PB. [Wisdom of the CROUD: Development and validation of a patient-level prediction model for opioid use disorder using population-level claims data.](http://dx.plos.org/10.1371/journal.pone.0228632) PLoS One. 2020 Feb 13;15(2):e0228632.

- Wang Q, Reps JM, Kostka KF, et al. [Development and validation of a prognostic model predicting symptomatic hemorrhagic transformation in acute ischemic stroke at scale in the OHDSI network.](http://dx.plos.org/10.1371/journal.pone.0226718) PLoS One. 2020 Jan 7;15(1):e0226718. 

- Suchard MA, Schuemie MJ, Krumholz HM, et al. [Comprehensive comparative effectiveness and safety of first-line antihypertensive drug classes: a systematic, multinational, large-scale analysis.](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(19)32317-7/fulltext) Lancet. 2019 Nov 16;394(10211):1816-1826.

- You SC, Jung S, Swerdel JN, Ryan PB, et al. [Comparison of First-Line Dual Combination Treatments in Hypertension: Real-World Evidence from Multinational Heterogeneous Cohorts.](https://e-kcj.org/DOIx.php?id=10.4070/kcj.2019.0173) Korean Circ J. 2020 Jan;50(1):52-68.

- Johnston SS, Morton JM, Kalsekar I, et al. [Using Machine Learning Applied to Real-World Healthcare Data for Predictive Analytics: An Applied Example in Bariatric Surgery.](https://www.sciencedirect.com/science/article/pii/S1098301519300737?via%3Dihub) Value Health. 2019 May;22(5):580-586. 

- Weinstein RB, Ryan PB, Berlin JA, et al. [Channeling Bias in the Analysis of Risk of Myocardial Infarction, Stroke, Gastrointestinal Bleeding, and Acute Renal Failure with the Use of Paracetamol Compared with Ibuprofen.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7434801/) Drug Saf. 2020 Sep;43(9):927-942.

- Vashisht R, Jung K, Schuler A, et al. [Association of hemoglobin a1c levels with use of sulfonylureas, dipeptidyl peptidase 4 inhibitors, and thiazolidinediones in patients with type 2 diabetes treated with metformin: Analysis from the observational health data sciences and informatics initiative.](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2698083) JAMA Network Open. 2018; 1: e181755.

- Ryan PB, Buse JB, Schuemie MJ, et al. [Comparative effectiveness of canagliflozin, SGLT2 inhibitors and non-SGLT2 inhibitors on the risk of hospitalization for heart failure and amputation in patients with type 2 diabetes mellitus: A real-world meta-analysis of 4 observational databases (OBSERVE-4D).](https://onlinelibrary.wiley.com/doi/full/10.1111/dom.13424) Diabetes, obesity & metabolism. 2018; 20: 2585-97.

- Yuan Z, DeFalco FJ, Ryan PB, et al. [Risk of lower extremity amputations in people with type 2 diabetes mellitus treated with sodium-glucose co-transporter-2 inhibitors in the USA: A retrospective cohort study.](https://onlinelibrary.wiley.com/doi/full/10.1111/dom.13115) Diabetes, obesity & metabolism. 2018; 20: 582-9.

- Weinstein RB, Ryan P, Berlin JA, et al. [Channeling in the Use of Nonprescription Paracetamol and Ibuprofen in an Electronic Medical Records Database: Evidence and Implications.](https://rd.springer.com/article/10.1007/s40264-017-0581-7) Drug safety. 2017; 40: 1279-92.

- Wang Y, Desai M, Ryan PB, et al. [Incidence of diabetic ketoacidosis among patients with type 2 diabetes mellitus treated with SGLT2 inhibitors and other antihyperglycemic agents.](https://www.sciencedirect.com/science/article/pii/S0168822716318629) Diabetes Res Clin Pract. 2017; 128: 83-90.

- Ryan PB, Schuemie MJ, Ramcharran D and Stang PE. [Atypical Antipsychotics and the Risks of Acute Kidney Injury and Related Outcomes Among Older Adults: A Replication Analysis and an Evaluation of Adapted Confounding Control Strategies](https://rd.springer.com/article/10.1007%2Fs40266-016-0430-x). Drugs & aging. 2017; 34: 211-9.

- Ramcharran D, Qiu H, Schuemie MJ, et al. [Atypical Antipsychotics and the Risk of Falls and Fractures Among Older Adults: An Emulation Analysis and an Evaluation of Additional Confounding Control Strategies.](https://journals.lww.com/psychopharmacology/Abstract/2017/04000/Atypical_Antipsychotics_and_the_Risk_of_Falls_and.9.aspx) J Clin Psychopharmacol. 2017; 37: 162-8.

- Boland MR, Parhi P, Li L, et al. [Uncovering exposures responsible for birth season - disease effects: a global study.](https://academic.oup.com/jamia/article/25/3/275/4265709) J Am Med Inform Assoc. 2017 Sep 28.

- Duke JD, Ryan PB, Suchard MA, et al. [Risk of angioedema associated with levetiracetam compared with phenytoin: Findings of the observational health data sciences and informatics research network.](https://onlinelibrary.wiley.com/doi/full/10.1111/epi.13828) Epilepsia. 2017; 58: e101-e6.


# Methods research

- Swerdel JN, Schuemie M, Murray G, et al. [PheValuator 2.0: Methodological improvements for the PheValuator approach to semi-automated phenotype algorithm evaluation](https://doi.org/10.1016/j.jbi.2022.104177) J Biomed Inform. 2022 Aug 19;104177.

- Schuemie MJ, Arshad F, Pratt N, et al. [Vaccine Safety Surveillance Using Routinely Collected Healthcare Data-An Empirical Evaluation of Epidemiological Designs](https://doi.org/10.3389/fphar.2022.893484) Front Pharmacol. 2022 Jul 6;13:893484.

- Ostropolets A, Ryan PB, Schuemie MJ, et al. [Characterizing Anchoring Bias in Vaccine Comparator Selection Due to Health Care Utilization With COVID-19 and Influenza: Observational Cohort Study](https://doi.org/10.2196/33099) JMIR Public Health Surveill
. 2022 Jun 17;8(6):e33099.

- Reps JM, Williams RD, Schuemie MJ, et al. [Learning patient-level prediction models across multiple healthcare databases: evaluation of ensembles for increasing model transportability](https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-022-01879-6) BMC Med Inform Decis Mak. 2022 May 25;22(1):142. doi: 10.1186/s12911-022-01879-6.

- Williams RD, Reps JM, Kors JA, et al. [Using Iterative Pairwise External Validation to Contextualize Prediction Model Performance: A Use Case Predicting 1-Year Heart Failure Risk in Patients with Diabetes Across Five Data Sources](https://doi.org/10.1007/s40264-022-01161-8) Drug Saf. 2022 May;45(5):563-570.

- Ostropolets A, Ryan P, Schuemie M, et al. [Differential anchoring effects of vaccination comparator selection: characterizing a potential bias due to healthcare utilization in COVID-19 versus influenza](https://doi.org/10.2196/33099) JMIR Public Health Surveill. 2022 Apr 26. doi: 10.2196/33099

- Ostropolets A, Li X, Makadia R, et al., [Factors Influencing Background Incidence Rate Calculation: Systematic Empirical Evaluation Across an International Network of Observational Databases](https://doi.org/10.3389/fphar.2022.814198) Front Pharmacol. 2022 Apr 26;13:814198.

- Li X, Lai LY, Ostropolets A, et al. [Bias, Precision and Timeliness of Historical (Background) Rate Comparison Methods for Vaccine Safety Monitoring: An Empirical Multi-Database Analysis](https://doi.org/10.3389/fphar.2021.773875) Front Pharmacol. 2021 Nov 24;12:773875. doi: 10.3389/fphar.2021.773875.

- Schuemie MJ, Chen Y, Madigan D, et al. [Combining cox regressions across a heterogeneous distributed research network facing small and zero counts](https://journals.sagepub.com/doi/10.1177/09622802211060518) Stat Methods Med Res. 2021 Nov 29. doi: 10.1177/09622802211060518.

- Reps JM, Ryan P, Rijnbeek PR. [Investigating the impact of development and internal validation design when training prognostic models using a retrospective cohort in big US observational healthcare data](https://bmjopen.bmj.com/lookup/pmidlookup?view=long&pmid=34952871) BMJ Open. 2021 Dec 24;11(12):e050146. doi: 10.1136/bmjopen-2021-050146.

- Khalid S, Yang C, Blacketer C, et al. [A standardized analytics pipeline for reliable and rapid development and validation of prediction models using observational health data](https://linkinghub.elsevier.com/retrieve/pii/S0169-2607(21)00468-5) Comput Methods Programs Biomed. 2021 Nov;211:106394. doi: 10.1016/j.cmpb.2021.106394.

- Reps JM, Kim C, Williams RD, et al. [Implementation of the COVID-19 Vulnerability Index Across an International Network of Health Care Data Sets: Collaborative External Validation Study.](https://medinform.jmir.org/2021/4/e21547/) JMIR Med Inform. 2021 Apr 5;9(4):e21547. doi: 10.2196/21547.

- Fortin SP, Johnston SS, Schuemie MJ. [Applied comparison of large-scale propensity score matching and cardinality matching for causal inference in observational research.](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-021-01282-1) BMC Med Res Methodol. 2021 May 24;21(1):109. doi: 10.1186/s12874-021-01282-1. 

- Reps JM, Rijnbeek P, Cuthbert A, et al. [An empirical analysis of dealing with patients who are lost to follow-up when developing prognostic models using a cohort design](https://doi.org/10.1186/s12911-021-01408-x) BMC Med Inform Decis Mak. 2021 Feb 6;21(1):43. doi: 10.1186/s12911-021-01408-x.

- Schuemie MJ, Weinstein R, Ryan PB, et al. [Quantifying bias in epidemiologic studies evaluating the association between acetaminophen use and cancer](https://doi.org/10.1016/j.yrtph.2021.104866) Regul Toxicol Pharmacol. 2021 Mar;120:104866. doi: 10.1016/j.yrtph.2021.104866.

- Thurin NH, Lassalle R, Schuemie M, et al. [Empirical assessment of case-based methods for identification of drugs associated with acute liver injury in the French National Healthcare System database (SNDS).](https://doi.org/10.1002/pds.5161) Pharmacoepidemiol Drug Saf. 2020 Oct 25. doi: 10.1002/pds.5161. 

- Schuemie MJ, Ryan PB, Pratt N, et al. [Large-scale evidence generation and evaluation across a network of databases (LEGEND): assessing validity using hypertension as a case study.](https://academic.oup.com/jamia/article/27/8/1268/5895564) J Am Med Inform Assoc. 2020 Aug 1;27(8):1268-1277.

- Thurin NH, Lassalle R, Schuemie M, et al. [Empirical assessment of case-based methods for identification of drugs associated with upper gastrointestinal bleeding in the French National Healthcare System database (SNDS).](https://doi.org/10.1002/pds.5038) Pharmacoepidemiol Drug Saf. 2020 Aug;29(8):890-903. doi: 10.1002/pds.5038.

- Reps JM, Williams RD, You SC, et al. [Feasibility and evaluation of a large-scale external validation approach for patient-level prediction in an international data network: validation of models predicting stroke in female patients newly diagnosed with atrial fibrillation.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7201646/) BMC Med Res Methodol. 2020 May 6;20(1):102.

- Schuemie MJ, Cepeda MS, Suchard MA, et al. [How Confident Are We About Observational Findings in Health Care: A Benchmark Study](https://hdsr.mitpress.mit.edu/pub/fxz7kr65) Harvard Data Science Review, 2(1).

- Schuemie MJ, Ryan PB, Man KKC, et al. [A plea to stop using the case-control design in retrospective database studies.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6771795/) Stat Med. 2019 Sep 30;38(22):4199-4208.

- Reps JM, Rijnbeek PR, Ryan PB. [Identifying the DEAD: Development and Validation of a Patient-Level Model to Predict Death Status in Population-Level Claims Data.](https://link.springer.com/article/10.1007%2Fs40264-019-00827-0) Drug Saf. 2019 May 3. 

- Reps JM, Schuemie MJ, Suchard MA, et al. [Design and implementation of a standardized framework to generate and evaluate patient-level prediction models using observational healthcare data.](https://academic.oup.com/jamia/article/25/8/969/4989437) J Am Med Inform Assoc. 2018;25(8):969-975.

- Schuemie MJ, Ryan PB, Hripcsak G, et al. [Improving reproducibility by using high-throughput observational studies with empirical calibration.](http://rsta.royalsocietypublishing.org/content/376/2128/20170356.long) Philosophical transactions Series A, Mathematical, physical, and engineering sciences. 2018; 376.

- Tian Y, Schuemie MJ and Suchard MA. [Evaluating large-scale propensity score performance through real-world and synthetic data experiments.](https://academic.oup.com/ije/advance-article-abstract/doi/10.1093/ije/dyy120/5043131) International journal of epidemiology. 2018.

- Schuemie MJ, Hripcsak G, Ryan PB, et al. [Empirical confidence interval calibration for population-level effect estimation studies in observational healthcare data.](http://www.pnas.org/content/115/11/2571.long) Proceedings of the National Academy of Sciences of the United States of America. 2018; 115: 2571-7.

- Schuemie MJ, Hripcsak G, Ryan PB, et al. [Robust empirical calibration of p-values using observational data.](https://onlinelibrary.wiley.com/doi/10.1002/sim.6977) Statistics in medicine. 2016; 35: 3883-8.

- Schuemie MJ, Ryan PB, DuMouchel W, et al. [Interpreting observational studies: why empirical calibration is needed to correct p-values.](https://onlinelibrary.wiley.com/doi/full/10.1002/sim.5925) Statistics in medicine. 2014; 33: 209-18.

