---
title: "Questions and Bug Reports"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

# Forums

Questions about HADES can be asked on the [OHDSI Forums](http://forums.ohdsi.org/).

# Bug reports

Bug reports should be files using the issue tracker of the misbehaving package:

- [Achilles issue tracker](https://github.com/ohdsi/Achilles/issues)

- [Andromeda issue tracker](https://github.com/ohdsi/Andromeda/issues)

- [BigKnn issue tracker](https://github.com/ohdsi/BigKnn/issues)

- [BrokenAdaptiveRidge issue tracker](https://github.com/ohdsi/BrokenAdaptiveRidge/issues)

- [Capr issue tracker](https://github.com/ohdsi/Capr/issues)

- [Characterization issue tracker](https://github.com/ohdsi/Characterization/issues)

- [CirceR issue tracker](https://github.com/ohdsi/CirceR/issues)

- [CohortDiagnostics issue tracker](https://github.com/ohdsi/CohortDiagnostics/issues)

- [CohortExplorer issue tracker](https://github.com/ohdsi/CohortExplorer/issues)

- [CohortGenerator issue tracker](https://github.com/ohdsi/CohortGenerator/issues)

- [CohortIncidence issue tracker](https://github.com/ohdsi/CohortIncidence/issues)

- [CohortMethod issue tracker](https://github.com/ohdsi/CohortMethod/issues)

- [Cyclops issue tracker](https://github.com/ohdsi/Cyclops/issues)

- [DatabaseConnector issue tracker](https://github.com/ohdsi/DatabaseConnector/issues)

- [DataQualityDashboard issue tracker](https://github.com/ohdsi/DataQualityDashboard/issues)

- [DeepPatientLevelPrediction issue tracker](https://github.com/ohdsi/DeepPatientLevelPrediction/issues)

- [EmpiricalCalibration issue tracker](https://github.com/ohdsi/EmpiricalCalibration/issues)

- [EnsemblePatientLevelPrediction issue tracker](https://github.com/ohdsi/EnsemblePatientLevelPrediction/issues)

- [Eunomia issue tracker](https://github.com/ohdsi/Eunomia/issues)

- [EvidenceSynthesis issue tracker](https://github.com/ohdsi/EvidenceSynthesis/issues)

- [FeatureExtraction issue tracker](https://github.com/ohdsi/FeatureExtraction/issues)

- [Hydra issue tracker](https://github.com/ohdsi/Hydra/issues)

- [IterativeHardThresholding issue tracker](https://github.com/ohdsi/IterativeHardThresholding/issues)

- [Keeper issue tracker](https://github.com/ohdsi/Keeper/issues)

- [MethodEvaluation issue tracker](https://github.com/ohdsi/MethodEvaluation/issues)

- [OhdsiSharing issue tracker](https://github.com/ohdsi/OhdsiSharing/issues)

- [OhdsiShinyModules issue tracker](https://github.com/ohdsi/OhdsiShinyModules/issues)

- [ParallelLogger issue tracker](https://github.com/ohdsi/ParallelLogger/issues)

- [PatientLevelPrediction issue tracker](https://github.com/ohdsi/PatientLevelPrediction/issues)

- [PhenotypeLibrary issue tracker](https://github.com/ohdsi/PhenotypeLibrary/issues)

- [PheValuator issue tracker](https://github.com/ohdsi/PheValuator/issues)

- [ResultModelManager issue tracker](https://github.com/ohdsi/ResultModelManager/issues)

- [ROhdsiWebApi issue tracker](https://github.com/ohdsi/ROhdsiWebApi/issues)

- [SelfControlledCaseSeries issue tracker](https://github.com/ohdsi/SelfControlledCaseSeries/issues)

- [SelfControlledCohort issue tracker](https://github.com/ohdsi/SelfControlledCohort/issues)

- [ShinyAppBuilder issue tracker](https://github.com/ohdsi/ShinyAppBuilder/issues)

- [SqlRender issue tracker](https://github.com/ohdsi/SqlRender/issues)

- [Strategus issue tracker](https://github.com/ohdsi/Strategus/issues)

- [TreatmentPatterns issue tracker](https://github.com/darwin-eu/TreatmentPatterns/issues)

