---
title: "Validation & Evaluation"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

# Validation

For validation, HADES mostly relies on an extensive set of unit tests executed as part of its continuous integration. This assures validity on a continuous basis, at every release. A good reference would be our recent HADES paper:

- Schuemie M, Reps J, Black A, et al. [Health-Analytics Data to Evidence Suite (HADES): Open-Source Software for Observational Research](https://ebooks.iospress.nl/doi/10.3233/SHTI231108) Studies in health technology and informatics. 2024 Jan 25:310:966-970. 


# Evaluation

The population-level estimation methods have been extensively evaluated using the OHDSI Methods Benchmark. The results are published in:

- Schuemie MJ, Cepeda MS, Suchard MA, et al. [How Confident Are We About Observational Findings in Health Care: A Benchmark Study](https://hdsr.mitpress.mit.edu/pub/fxz7kr65) Harvard Data Science Review, 2(1).

The results of the evaluation can be reviewed in [an interactive web application](https://data.ohdsi.org/MethodEvalViewer/).
