---
title: 'Packages'
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

Below are the packages included in HADES. For each package a link is provided with more information, including instructions on how to install and use the package.

</ul>
<h2 id="pkg_header">Population-level estimation</h2>
<ul id="pkg">
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/CohortMethod">CohortMethod</a></h4>New-user cohort studies using large-scale regression for propensity and outcome models.</br><a href="https://ohdsi.github.io/CohortMethod">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/SelfControlledCaseSeries">SelfControlledCaseSeries</a></h4>Self-Controlled Case Series analysis using few or many predictors, includes splines for age and seasonality.</br><a href="https://ohdsi.github.io/SelfControlledCaseSeries">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/SelfControlledCohort">SelfControlledCohort</a></h4>A self-controlled cohort design, where time preceding exposure is used as control.</br><a href="https://ohdsi.github.io/SelfControlledCohort">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/CaseControl">CaseControl</a></h4>Case-control studies, matching controls on age, gender, provider, and visit date. Allows nesting of the study in another cohort.</br><a href="https://ohdsi.github.io/CaseControl">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/CaseCrossover">CaseCrossover</a></h4>Case-crossover design including the option to adjust for time-trends in exposures (so-called case-time-control).</br><a href="https://ohdsi.github.io/CaseCrossover">Learn more...</a></li>
</ul>
<h2 id="pkg_header">Patient-level prediction</h2>
<ul id="pkg">
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/PatientLevelPrediction">PatientLevelPrediction</a></h4>Build and evaluate predictive models for user-specified outcomes, using a wide array of machine learning algorithms.</br><a href="https://ohdsi.github.io/PatientLevelPrediction">Learn more...</a></li>
</ul>
<h2 id="pkg_header">Evidence Quality</h2>
<ul id="pkg">
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/EmpiricalCalibration">EmpiricalCalibration</a></h4>Use negative control exposure-outcome pairs to profile and calibrate a particular analysis design.</br><a href="https://ohdsi.github.io/EmpiricalCalibration">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/MethodEvaluation">MethodEvaluation</a></h4>Use real data and established reference sets as well as simulations injected in real data to evaluate the performance of methods.</br><a href="https://ohdsi.github.io/MethodEvaluation">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/CohortDiagnostics">CohortDiagnostics</a></h4>Generate a wide set of diagnostics to evaluate cohort definitions against databases in the CDM.</br><a href="https://ohdsi.github.io/CohortDiagnostics">Learn more...</a></li>
</ul>
<h2 id="pkg_header">Supporting packages</h2>
<ul id="pkg">
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/Cyclops">Cyclops</a></h4>Highly efficient implementation of regularized logistic, Poisson and Cox regression.</br><a href="https://ohdsi.github.io/Cyclops">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/DatabaseConnector">DatabaseConnector</a></h4>Connect directly to a wide range of database platforms, including SQL Server, Oracle, and PostgreSQL.</br><a href="https://ohdsi.github.io/DatabaseConnector">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/SqlRender">SqlRender</a></h4>Generate SQL on the fly for the various SQL dialects.</br><a href="https://ohdsi.github.io/SqlRender">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/ParallelLogger">ParallelLogger</a></h4>Support for parallel computation with logging to console, disk, or e-mail.</br><a href="https://ohdsi.github.io/ParallelLogger">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/FeatureExtraction">FeatureExtraction</a></h4>Automatically extract large sets of features for user-specified cohorts using data in the CDM.</br><a href="https://ohdsi.github.io/FeatureExtraction">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/Andromeda">Andromeda</a></h4>Storing very large data objects on a local drive, while still making it possible to manipulate the data in an efficient manner.</br><a href="https://ohdsi.github.io/Andromeda">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/BigKnn">BigKnn</a></h4>A large scale k-nearest neighbor classifier using the Lucene search engine.</br><a href="https://ohdsi.github.io/BigKnn">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/ROhdsiWebApi">ROhdsiWebApi</a></h4>Interact with OHDSI WebAPI web services.</br><a href="https://ohdsi.github.io/ROhdsiWebApi">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/OhdsiSharing">OhdsiSharing</a></h4>Securely sharing (large) files between OHDSI collaborators.</br><a href="https://ohdsi.github.io/OhdsiSharing">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/Hydra">Hydra</a></h4>Hydrating package skeletons into executable R study packages based on specifications in JSON format.</br><a href="https://ohdsi.github.io/Hydra">Learn more...</a></li>
<li><h4><i class="fas  fa-cube "></i> <a href="https://ohdsi.github.io/Eunomia">Eunomia</a></h4>A standard CDM dataset for testing and demonstration purposes that runs on an embedded SQLite database.</br><a href="https://ohdsi.github.io/Eunomia">Learn more...</a></li>
</ul>
